name: TDVT Demo CI
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{matrix.os}}
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install TDVT
      run: |
        python -m pip install --upgrade pip
        pip install -e tdvt/
    - name: Run TDVT unit tests
      run: |
        cd tdvt/test
        python tdvt_test.py -v CommandLineTest ConfigTest DiffTest PrintConfigurationsTest
