name: Python application

on: [push]

jobs:
  build:
    strategy:
      matrix:
        java: ['1.8', '1.10', '1.12']
        os: [windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Set up Java
      uses: actions/setup-java@v1.0.0
      with:
        version: ${{matrix.java}}
    - name: Install TDVT
      run: |
        python -m pip install --upgrade pip
        pip install -e tdvt/
    - name: Install Connector Packager
      run: |
          cd connector-packager
          python setup.py install
    - name: Run TDVT unit tests
      run: |
        cd tdvt/test
        python tdvt_test.py -v CommandLineTest ConfigTest DiffTest PrintConfigurationsTest
    - name: Run Connector Packager unit tests with JDK ${{ matrix.java }}
      run: |
        cd connector-packager
        python setup.py test
